package com.woniuxy.domain;
// Generated 2019-6-20 19:55:38 by Hibernate Tools 5.4.2.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer eno;
	private Dept dept;
	private String ename;
	private Date hiredate;
	private BigDecimal sal;

	public Emp() {
	}

	public Emp(Dept dept, String ename, Date hiredate, BigDecimal sal) {
		this.dept = dept;
		this.ename = ename;
		this.hiredate = hiredate;
		this.sal = sal;
	}

	public Integer getEno() {
		return this.eno;
	}

	public void setEno(Integer eno) {
		this.eno = eno;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	public BigDecimal getSal() {
		return this.sal;
	}

	public void setSal(BigDecimal sal) {
		this.sal = sal;
	}

}
